[project]
name = "pg"
version = "0.1.0"
description = "Simple password generator"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "click>=7.0.0",
]

[project.scripts]
pg = "pg:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
